apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fib-node-graphtuitous
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fib-node-graphtuitous
    app.kubernetes.io/part-of: graphtuitous
  name: fib-node-graphtuitous
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fib-node-graphtuitous
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fib-node-graphtuitous
    spec:
      containers:
      - image: quay.io/northdepot/user1-tenant/graphtuitous/fib-node-graphtuitous@sha256:d42f649f58f156ca3846af36dd75b7945e71958cfbecf836c5f51d3563178b3e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
