apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fib-go-graphtuitous
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/northdepot/user1-tenant/graphtuitous/fib-go-graphtuitous@sha256:61c20f53b7dec33b28031230822a8b00e6f2ecebcfe09a109be3ed34bbf2aaa9
        name: container-image
        resources: {}
status: {}
