apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: haproxy-graphtuitous
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: haproxy-graphtuitous
    app.kubernetes.io/part-of: graphtuitous
  name: haproxy-graphtuitous
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: haproxy-graphtuitous
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: haproxy-graphtuitous
    spec:
      containers:
      - image: quay.io/northdepot/user1-tenant/graphtuitous/haproxy-graphtuitous@sha256:e743abbce58eae809805c068b0f466734ebbd84f197000e0f3295974a5a9130d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
