apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fib-node-graphtuitous
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fib-node-graphtuitous
    app.kubernetes.io/part-of: graphtuitous
  name: fib-node-graphtuitousfgnu
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: fib-node-graphtuitous
    weight: null
status: {}
